name: Bridgecrew
on:
  pull_request:
  push:
    branches:
      - dev
jobs: 
  scan:
    
    runs-on: ubuntu-latest
    env: 
     PRISMA_API_URL: https://api.eu.prismacloud.io
    
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Run Bridgecrew 
      id: Bridgecrew
      uses: bridgecrewio/bridgecrew-action@master
      with:
        api-key: ${{ secrets.BC_API_KEY }}
        soft_fail: false
        directory: .
