name: Bridgecrew
on:
  pull_request:
  push:
    branches: [master, dev]
jobs: 
  scan:
    
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.8] 
    steps:

    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
       python-version: ${{ matrix.python-version }}
    - name: Install Check and Scan IaC
      run: |
       pip install -U checkov
       checkov -d . --framework terraform -b master --prisma-api-url https://api.eu.prismacloud.io --bc-api-key ${{ secrets.BC_API_KEY }}
